### ISSUE TITLE
Research alternatives to enforce code coverage in CI/CD

### ISSUE THREAD

**Issue by julien-marchand** [ConsenSys/orchestrate#362]
Interesting alternatives which integrates natively with CircleCI and has free tier for open-source projects

https://circleci.com/developer/orbs/orb/codecov/codecov

https://circleci.com/blog/making-code-coverage-easy-to-see-with-the-codecov-orb/

**Comment by ggarri** [comment]
Interesting alternatives which integrates natively with CircleCI and has free tier for open-source projects

https://circleci.com/blog/making-code-coverage-easy-to-see-with-the-codecov-orb/
