### ISSUE TITLE
Update deployment & e2e for the Key Manager

### ISSUE THREAD

**Issue by julien-marchand** [ConsenSys/orchestrate#628]
# Acceptance test

- [x] Update `orchestrate-helm` to use the KM as a dependency
- [x] Update `orchestrate-kubernetes` with the KM
- [x] Check e2e tests passing with the KM

**Comment by 6l20** [comment]
Remaining issues are related to quorum and besu nodes :

{"log.level":"error","@timestamp":"2022-01-05T07:57:01.143Z","log.logger":"nodes","message":"failed to fetch chainID","error":{"message":"Invalid downstream HTTP status"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-05T07:57:01.143Z","log.logger":"auth.accesslog","message":"127.0.0.1 - - [05/Jan/2022:07:57:01 +0000] \"POST /nodes/quorum-node HTTP/1.1\" 200 150\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-01-05T07:57:01.295Z","log.logger":"nodes","message":"failed to fetch chainID","error":{"message":"Invalid downstream HTTP status"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-05T07:57:01.328Z","log.logger":"auth.accesslog","message":"127.0.0.1 - - [05/Jan/2022:07:57:01 +0000] \"POST /nodes/quorum-node HTTP/1.1\" 200 150\n","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-05T07:57:01.428Z","log.logger":"auth.accesslog","message":"127.0.0.1 - - [05/Jan/2022:07:57:01 +0000] \"POST /nodes/quorum-node HTTP/1.1\" 200 183\n","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-05T07:57:01.526Z","log.logger":"auth.accesslog","message":"127.0.0.1 - - [05/Jan/2022:07:57:01 +0000] \"POST /nodes/quorum-node HTTP/1.1\" 200 182\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-01-05T07:57:01.727Z","log.logger":"nodes","message":"failed to fetch gas price","error":{"message":"Invalid downstream HTTP status"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-05T07:57:01.731Z","log.logger":"auth.accesslog","message":"127.0.0.1 - - [05/Jan/2022:07:57:01 +0000] \"POST /nodes/quorum-node HTTP/1.1\" 200 150\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-01-05T07:57:01.858Z","log.logger":"nodes","message":"failed to fetch gas price","error":{"message":"Invalid downstream HTTP status"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-05T07:57:01.858Z","log.logger":"auth.accesslog","message":"127.0.0.1 - - [05/Jan/2022:07:57:01 +0000] \"POST /nodes/quorum-node HTTP/1.1\" 200 150\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-01-05T07:57:02.018Z","log.logger":"nodes","message":"failed to fetch gas price","error":{"message":"Invalid downstream HTTP status"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-05T07:57:02.018Z","log.logger":"auth.accesslog","message":"127.0.0.1 - - [05/Jan/2022:07:57:01 +0000] \"POST /nodes/quorum-node HTTP/1.1\" 200 150\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-01-05T07:57:02.134Z","log.logger":"nodes","message":"failed to fetch gas price","error":{"message":"Invalid downstream HTTP status"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-05T07:57:02.134Z","log.logger":"auth.accesslog","message":"127.0.0.1 - - [05/Jan/2022:07:57:02 +0000] \"POST /nodes/quorum-node HTTP/1.1\" 200 150\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-01-05T07:57:02.246Z","log.logger":"nodes","message":"failed to fetch gas price","error":{"message":"Invalid downstream HTTP status"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-05T07:57:02.246Z","log.logger":"auth.accesslog","message":"127.0.0.1 - - [05/Jan/2022:07:57:02 +0000] \"POST /nodes/quorum-node HTTP/1.1\" 200 150\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-01-05T07:57:02.360Z","log.logger":"nodes","message":"failed to fetch gas price","error":{"message":"Invalid downstream HTTP status"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-05T07:57:02.360Z","log.logger":"auth.accesslog","message":"127.0.0.1 - - [05/Jan/2022:07:57:02 +0000] \"POST /nodes/quorum-node HTTP/1.1\" 200 150\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-01-05T07:57:02.643Z","log.logger":"nodes","message":"failed to fetch transaction count (EEA transaction)","error":{"message":"Invalid downstream HTTP status"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-05T07:57:02.643Z","log.logger":"auth.accesslog","message":"127.0.0.1 - - [05/Jan/2022:07:57:02 +0000] \"POST /nodes/besu-node HTTP/1.1\" 200 150\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-01-05T07:57:02.878Z","log.logger":"nodes","message":"failed to fetch transaction count (EEA transaction)","error":{"message":"Invalid downstream HTTP status"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-05T07:57:02.878Z","log.logger":"auth.accesslog","message":"127.0.0.1 - - [05/Jan/2022:07:57:02 +0000] \"POST /nodes/besu-node HTTP/1.1\" 200 150\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-01-05T07:57:02.989Z","log.logger":"nodes","message":"failed to fetch transaction count (EEA transaction)","error":{"message":"Invalid downstream HTTP status"},"ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-01-05T07:57:02.989Z","log.logger":"auth.accesslog","message":"127.0.0.1 - - [05/Jan/2022:07:57:02 +0000] \"POST /nodes/besu-node HTTP/1.1\" 200 150\n","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-01-05T07:57:03.150Z","log.logger":"nodes","message":"failed to fetch transaction count (EEA transaction)","error":{"message":"Invalid downstream HTTP status"},"ecs.version":"1.6.0"}
