### ISSUE TITLE
[Solidity] Compatibility with latest versions

### ISSUE THREAD

**Issue by darioAnongba** [ConsenSys/orchestrate#789]
### Summary / User Story

Solidity is currently in version `0.8.11`. Orchestrate only supports Solidity version up to 0.5.x because we implemented our own way of parsing the ABI. We should stop with the custom implementation and rely on go-ethereum to parse the ABI. The goal is to remove (or stop using) the `methods` table.

### Pre-requisites

Be aware of Solidity breaking changes between new versions: https://docs.soliditylang.org/en/v0.8.11/

## Business Value
Support all versions of Solidity

### Acceptance Criteria

- [ ] Register a contract containing AbiEncoderV2 usage
- [ ] Register a contract using the `fallback` function
- [ ] Verify that all the new features are supported

**Comment by julien-marchand** [comment]
Duplicate of #756
