### ISSUE TITLE
Use go-web3 to decode logs

### ISSUE THREAD

**Issue by ggarri** [ConsenSys/orchestrate#884]
Rewrite current in-house logic to decode logs in `chain-listener` by go-web3 in order to reduce maintenance effort on our side

## Acceptance criteria

- [ ] Check that structs can be decoded

**Comment by darioAnongba** [comment]
Before going to go-web3 we could try to see if go-ethereum can handle that using: https://github.com/ethereum/go-ethereum/blob/master/accounts/abi/bind/base.go
